# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rntwilioexample' do

  use_frameworks!
  
  pod 'TwilioVideo', '~> 1.0.1'
  pod 'PureLayout'
  pod 'TWTwilioVideoReactNative', :path => '../../'

end
